"use client";
import { Scope, getBaseApplicationContext } from "ironbean";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ContextProvider } from "./contextHistory";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const pageScope = Scope.create("page");
export default function RootLayout({ children }: { children: React.ReactNode }) {
    const context = getBaseApplicationContext();

    return (
        <html lang="en">
            <body className={inter.className}>
                <ContextProvider context={getBaseApplicationContext()}>
                    <nav>
                        <ul style={{ display: "flex", gap: "2rem" }}>
                            <li>
                                <Link href="/">Home</Link>
                            </li>
                            <li>
                                <Link href="/page1">Page 1</Link>
                            </li>
                            <li>
                                <Link href="/page2">Page 2</Link>
                            </li>
                            <li>
                                <Link href="/page1scoped">Page 1 scoped</Link>
                            </li>
                            <li>
                                <Link href="/page2scoped">Page 2 scoped</Link>
                            </li>
                        </ul>
                    </nav>
                    <br />
                    <br />
                    {children}
                </ContextProvider>
            </body>
        </html>
    );
}
